services:
  app:
    container_name: food-moo-duu-app
    build:
      context: ../..
      dockerfile: Dockerfile
    command: python main.py --non-interactive --top-k 5
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../..:/app
