services:
  layer1-intent-context:
    container_name: food-moo-duu-layer1
    build:
      context: ../..
      dockerfile: Dockerfile
    command: python -m src.layer1_intent_context.run_layer1 --all-datasets --message "Toi muon mon nong cho toi nay" --top-k 8 --raw-threshold 0.2 --context-threshold 0.1
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../..:/app
