services:
  layer3-genetic-response:
    container_name: food-moo-duu-layer3
    build:
      context: ../..
      dockerfile: Dockerfile
    command: python -m src.layer3_genetic_response.run_layer3 --repeat 2
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../data:/app/data
